# This is a basic workflow to help you get started with Actions

name: Increment version

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_BOT_PAT }}
          ref: ${{ github.event.release.head.ref }}
          
      - run: git config --global user.name '$GITHUB_ACTOR'
      - run: git config --global user.email '$GITHUB_ACTOR@users.noreply.github.com'
      
      - name: Increment version (${{ github.event.release.tag_name }})
        run: |
          npm config set git-tag-version false
          npm config set commit-hooks false
          npm version ${{ github.event.release.tag_name }}
        
      - name: Commit changes
        run: |
          git add .
          git commit -m "[RELEASE] ${{ github.event.release.tag_name }}"
          git push
        
